# Site settings
title: Vatsal Tewari
name: Vatsal Tewari
email: vatsal0147@gmail.com
description: "Sociology MA candidate at JNU. Research interests in digital transformation, social media's impact on community formation and rural development."
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://your-github-Vat69er.github.io" # a.k.a. "permalink"

# Social media profiles
github_username:  Vat69er
linkedin_username: Vatsal Tewari # (if you have one)

# A path to your avatar (profile picture)
# 1. Create a folder named "images" in your repository
# 2. Upload a professional headshot to it (e.g., "profile.jpg")
# 3. Change the path below to match
avatar: "/images/profile.jpg"

# DO NOT CHANGE THE FOLLOWING
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
